spring:
  application:
    name: cart
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

---
eureka:
  instance:
    appname: cart-service
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server.port: 8000

---
spring:
  profiles: cart-service-replica01
eureka:
  instance:
    appname: cart-service
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server.port: 8001

---
spring:
  profiles: cart-service-replica02
eureka:
  instance:
    appname: cart-service
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server.port: 8002
